# This file is not imported into your NixOS configuration. It is only used for the agenix CLI.
# agenix use the public keys defined in this file to encrypt the secrets.
# and users can decrypt the secrets by any of the corresponding private keys.

let
  # Get system's ssh public key by command:
  #    cat /etc/ssh/ssh_host_ed25519_key.pub
  # If you do not have this file, you can generate all the host keys by command:
  #    sudo ssh-keygen -A
  nixosryanai = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINQFg4Syxmy28DqLDAbw/gLqRfpVi/myXp4ubge+l657 root@nixos";

  # A key for recovery purpose, generated by `ssh-keygen -t ed25519 -a 256 -C "ryan@agenix-recovery"` with a strong passphrase
  # and keeped it offline in a safe place.
  recovery_key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHnIGH+653Oe+GQaA8zjjj7HWMWp7bWXed4q5KqY4nqG ryan@agenix-recovery";
  systems = [
    nixosryanai

    recovery_key
  ];
  users = [
    nixosryanai recovery_key
  ];
  in
{
  "nix-access-tokens.age".publicKeys = users ++ systems;
  "ryan4yin-gpg-subkeys.priv.age".publicKeys = users ++ systems;
  "wg-business.conf.age".publicKeys = users ++ systems;
  "smb-credentials.age".publicKeys = users ++ systems;
  "ssh-key-romantic.age".publicKeys = users ++ systems;
  "rclone.conf.age".publicKeys = users ++ systems;
  "public/ryan4yin-gpg-keys-2014-01-27.pub.age".publicKeys = users ++ systems;
  "alias-for-work.nushell.age".publicKeys = users ++ systems;
  "alias-for-work.bash.age".publicKeys = users ++ systems;
  "ryan4yin-gpg-subkeys-2024-01-27.priv.age.age".publicKeys = users ++ systems;

}
